# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('1a5c48f04fdee8080f4b5d8412d66ee9_MTQxMzI4MjAxMi0xMC0wOSAxNDowMjowMS41Mzk2Nzk')
  end)
end
